### PR TITLE
Fix name in pyproject.toml

### PR DESCRIPTION
**Pull request by alkino**
Otherwise, we got an error when trying to install sphinx.

```Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "<pip-setuptools-caller>", line 34, in <module>
  File "./setup.py", line 116, in <module>
    setup(
  File "./venv/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 507, in setup
    return setuptools.setup(**kw)
  File "./venv/lib/python3.10/site-packages/setuptools/__init__.py", line 86, in setup
    _install_setup_requires(attrs)
  File "./venv/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "./venv/lib/python3.10/site-packages/setuptools/dist.py", line 875, in fetch_build_eggs
    resolved_dists = pkg_resources.working_set.resolve(
  File "./venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 802, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (sphinxcontrib.applehelp 1.0.3 (./.eggs/sphinxcontrib.applehelp-1.0.3-py3.10.egg), Requirement.parse('sphinxcontrib-applehelp'), {'sphinx'})
```

### CODE REVIEW

**Comment by alkino** [comment]
This is a blind fix

**Comment by rigogsilva** [comment]
I think this is causing an infinite loop when using poetry install sphinx.

   1: selecting sphinxcontrib.applehelp (1.0.3)
   1: selecting sphinxcontrib.applehelp (1.0.3)
   1: selecting sphinxcontrib.applehelp (1.0.3)
   1: selecting sphinxcontrib.applehelp (1.0.3)
   1: selecting sphinxcontrib.applehelp (1.0.3)
   1: selecting sphinxcontrib.applehelp (1.0.3)
   1: selecting sphinxcontrib.applehelp (1.0.3)
   1: selecting sphinxcontrib.applehelp (1.0.3)
   1: selecting sphinxcontrib.applehelp (1.0.3)
   1: selecting sphinxcontrib.applehelp (1.0.3)
   1: selecting sphinxcontrib.applehelp (1.0.3)
   1: selecting sphinxcontrib.applehelp (1.0.3)
...
This goes on forever and it never resolves.

**Comment by alenrajsp** [comment]
> I think this is causing an infinite loop when using poetry install sphinx.
> 
> 1: selecting sphinxcontrib.applehelp (1.0.3) 1: selecting sphinxcontrib.applehelp (1.0.3) 1: selecting sphinxcontrib.applehelp (1.0.3) 1: selecting sphinxcontrib.applehelp (1.0.3) 1: selecting sphinxcontrib.applehelp (1.0.3) 1: selecting sphinxcontrib.applehelp (1.0.3) 1: selecting sphinxcontrib.applehelp (1.0.3) 1: selecting sphinxcontrib.applehelp (1.0.3) 1: selecting sphinxcontrib.applehelp (1.0.3) 1: selecting sphinxcontrib.applehelp (1.0.3) 1: selecting sphinxcontrib.applehelp (1.0.3) 1: selecting sphinxcontrib.applehelp (1.0.3) ... This goes on forever and it never resolves.

I am having the same problem.

**Comment by FelixGSE** [comment]
We are facing the same issue. @alkino Are you working on this / Do you need support? @AA-Turner Is there something you can do here - I noticed you made the commit 2 weeks ago

**Comment by alkino** [comment]
Not really. I don't really understand what's going on. You can take ownership of my PR. For now i stick to the previous version.

**Comment by alenrajsp** [comment]
@alkino I believe the problem is the following.

1. The name of this project on pypi is [sphinxcontrib.applehelp](https://pypi.org/project/sphinxcontrib.applehelp/) the same name is present in your [pyproject.toml](https://github.com/sphinx-doc/sphinxcontrib-applehelp/blob/master/pyproject.toml)
2. Your previous name of the package was (sphinxcontrib-applehelp)[https://github.com/sphinx-doc/sphinxcontrib-applehelp/commit/b11afda3eb587a8eb18a931892046137f46df717]. 
3. The name used in Sphinx is [sphinxcontrib-applehelp](https://github.com/sphinx-doc/sphinx/blob/master/pyproject.toml).

The name **sphinxcontrib.applehelp** vs **sphinxcontrib-applehelp**, leads to name resolving issues in many of the package managers... While **pypi** platform of course allows renaming the package (switching minus and dot), the same is not valid for many of the package managers.

**Comment by AA-Turner** [comment]
I've released 1.0.4 which should solve this problem.

A

**Comment by alkino** [comment]
Thanks a lot

**Pull request closed without merging**
